In [2]:
import os
os .listdir()

['.ipynb_checkpoints',
 'appendfile.py',
 'basics.py',
 'basicspip.py',
 'clock.py',
 'conditionals.py',
 'convertandsumup.py',
 'copyfiletofile.py',
 'createfile.py',
 'data.txt',
 'datatxt.py',
 'differentfilderfile.py',
 'file.py',
 'file2.py',
 'files',
 'filewrite.py',
 'first90.py',
 'first90.txt',
 'forloops.py',
 'fruits.txt',
 'fruits2.txt',
 'functionfile1.py',
 'kwargs.py',
 'kwargsvalues.py',
 'listcomprehension.py',
 'main.py',
 'mean.py',
 'my_program.py',
 'onlynumbers.py',
 'onlypositivenumbers.py',
 'openfilewith.py',
 'printlinesfruit.py',
 'stringsprocessed.py',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'temps.py',
 'temps2.py',
 'temps3.py',
 'test1.ipynb',
 'test2.ipynb',
 'test3.ipynb',
 'textprogram.py',
 'Untitled.ipynb',
 'while.py',
 'zeroinstead.py']

In [3]:
import pandas

In [5]:
df3 = pandas.read_excel ("supermarkets.xlsx", sheet_name=0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [7]:
df4=pandas.read_csv("supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [10]:
df5=pandas.read_csv("supermarkets-semi-colons.txt", sep=";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [17]:
df8 = pandas.read_csv("data.txt", header = None)
df8

ParserError: Error tokenizing data. C error: Expected 2 fields in line 2, saw 3


In [20]:
df7 = pandas.read_json("supermarkets.json")
df7

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [22]:
df7.loc["735 Dolores St":"332 Hill St", "Country": "ID"]
df7=df7.set_index("Address")
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [23]:
df7.loc["735 Dolores St":"332 Hill St", "Country": "ID"]
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [25]:
list(df7.loc[:,"Country"])
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [26]:
df7.iloc[1:3,1:3]

City             State
Address                                        
735 Dolores St  San Francisco          CA 94119
332 Hill St     San Francisco  California 94114

In [28]:
len(df7.index)

6

In [31]:
df7["Continent"]=df7.shape[0]*["North America"]
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

In [33]:
df7["Continent"]=df7["Country"]+"," + "North America"
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees          Continent  
Address                                        
3666 21st St             8  USA,North America  
735 Dolores St          15  USA,North America  
332 Hill St             25  USA,North America  
3995 23rd St            10  USA,North America  
1056 Sanchez St         12  USA,North America  
551 Alvarado St         20  USA,North America

In [36]:
df7_t=df7.T
df7_t

Address         3666 21st St     735 Dolores St        332 Hill St  \
ID                         1                  2                  3   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114           CA 94119   California 94114   
Country                  USA                USA                USA   
Name                 Madeira        Bready Shop        Super River   
Employees                  8                 15                 25   
Continent  USA,North America  USA,North America  USA,North America   

Address         3995 23rd St    1056 Sanchez St    551 Alvarado St  
ID                         4                  5                  6  
City           San Francisco      San Francisco      San Francisco  
State               CA 94114         California           CA 94114  
Country                  USA                USA                USA  
Name              Ben's Shop            Sanchez         Richvalley  
Employees                 10                 12                 20  
Continent  USA,North America  USA,North America  USA,North America

In [37]:
df7_t["My Address"]=["My City","My Country",10,7,"My Shop","My State", "My Continent"]

In [38]:
df7_t

Address         3666 21st St     735 Dolores St        332 Hill St  \
ID                         1                  2                  3   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114           CA 94119   California 94114   
Country                  USA                USA                USA   
Name                 Madeira        Bready Shop        Super River   
Employees                  8                 15                 25   
Continent  USA,North America  USA,North America  USA,North America   

Address         3995 23rd St    1056 Sanchez St    551 Alvarado St  \
ID                         4                  5                  6   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114         California           CA 94114   
Country                  USA                USA                USA   
Name              Ben's Shop            Sanchez         Richvalley   
Employees                 10                 12                 20   
Continent  USA,North America  USA,North America  USA,North America   

Address      My Address  
ID              My City  
City         My Country  
State                10  
Country               7  
Name            My Shop  
Employees      My State  
Continent  My Continent

In [39]:
df7=df7_t.T

In [40]:
df7

ID           City             State Country  \
Address                                                             
3666 21st St           1  San Francisco          CA 94114     USA   
735 Dolores St         2  San Francisco          CA 94119     USA   
332 Hill St            3  San Francisco  California 94114     USA   
3995 23rd St           4  San Francisco          CA 94114     USA   
1056 Sanchez St        5  San Francisco        California     USA   
551 Alvarado St        6  San Francisco          CA 94114     USA   
My Address       My City     My Country                10       7   

                        Name Employees          Continent  
Address                                                    
3666 21st St         Madeira         8  USA,North America  
735 Dolores St   Bready Shop        15  USA,North America  
332 Hill St      Super River        25  USA,North America  
3995 23rd St      Ben's Shop        10  USA,North America  
1056 Sanchez St      Sanchez        12  USA,North America  
551 Alvarado St   Richvalley        20  USA,North America  
My Address           My Shop  My State       My Continent

In [1]:
import geopy

In [2]:
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'Geocodio',
 'Geokeo',
 'Geolake',
 'GoogleV3',
 'Here',
 'HereV7',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'What3WordsV3',
 'Woosmap',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [3]:
from geopy.geocoders import Nominatim

In [4]:
nom=Nominatim()

ConfigurationError: Using Nominatim with default or sample `user_agent` "geopy/2.4.1" is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`.

In [5]:
nom.geocode("3995 2rd St, San Francisco, CA 94114")

NameError: name 'nom' is not defined

In [6]:
import numpy

In [8]:
n=numpy.arange(27) 

In [9]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [10]:
n=numpy.arange(27) 

In [11]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [13]:
print (n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [15]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [1]:
import cv2

In [2]:
im_g=cv2.imread("smallgray.png",0)

In [3]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [5]:
a[0:2]

NameError: name 'a' is not defined

In [6]:
im_g=cv2.imread("smallgray.png",2)

In [8]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
im_g.shape

(3, 5)

In [10]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [13]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [14]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
